# Generated by Django 3.1.7 on 2021-03-29 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('poster', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('releasetime', models.CharField(max_length=100)),
                ('introduction', models.CharField(max_length=1000)),
                ('directors', models.CharField(max_length=100)),
                ('writers', models.CharField(max_length=100)),
                ('actors', models.CharField(max_length=100)),
            ],
        ),
    ]
