# Generated by Django 3.1.7 on 2021-04-14 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='capital',
            field=models.CharField(default='&', max_length=1),
            preserve_default=False,
        ),
    ]
