# Generated by Django 2.2.20 on 2021-04-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0005_remove_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='20171300007@mail.ynu.edu.cn', max_length=32),
            preserve_default=False,
        ),
    ]
