# Generated by Django 3.1.7 on 2021-05-03 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0006_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.CharField(default='user_photo', max_length=100),
            preserve_default=False,
        ),
    ]
