# Generated by Django 3.1.7 on 2021-05-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0009_user_occupation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
