# Generated by Django 3.1.7 on 2021-05-05 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0013_user_zip'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.CharField(default='25', max_length=10),
            preserve_default=False,
        ),
    ]
